name: nlp
channels:
  - defaults
dependencies:
  - pip=10.0.1
  - python=3.6.5
  - pip:
    - absl-py==0.2.2
    - astor==0.6.2
    - bleach==1.5.0
    - gast==0.2.0
    - grpcio==1.12.1
    - h5py==2.8.0
    - html5lib==0.9999999
    - keras==2.2.0
    - keras-applications==1.0.2
    - keras-preprocessing==1.0.1
    - markdown==2.6.11
    - numpy==1.14.4
    - protobuf==3.5.2.post1
    - pyyaml==3.12
    - scikit-learn==0.19.1
    - scipy==1.1.0
    - six==1.11.0
    - sklearn==0.0
    - tensorboard==1.8.0
    - tensorflow==1.8.0
    - termcolor==1.1.0
    - werkzeug==0.14.1

